# Known invalid or missed Message-IDs
# 'domain' 'Message-ID regexp'

1c-bitrix.ru
alibaba.com /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}-0$/
aliexpress.com /^(?:(?:[0-9]{14,16}|[a-z]{4}(?:COWS|UTT)_[0-9]{3,6}_(?:(?:[0-9]{7,8}|0)_)?)[$])?[a-f0-9]{32}$/
beeline.ru /^<[A-z0-9+]{18}>$/
cdek.ru
citilink.ru
noreply.esphere.ru
etpgpb.ru
noreply.etprf.ru
freshports.org
rkn.gov.ru
garant.ru
is-zakupki.com
kassir.ru
mail-us.jira.com /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/
mirtesen.ru
fcod.nalog.ru
www.nalog.ru
otc.ru
news.ozon.ru /^[A-z0-9+/]{32}$/
sender.ozon.ru /^[A-z0-9+/]{32}$/
professionali.ru
psbank.ru
qiwi.ru
robokassa.ru
client.rostelecom.ru
sberbank-ast.ru
taxcom.ru
crm.taxcom.ru
wildberries.ru /^[a-f0-9]{8}(?:-[a-f0-9]{4}){3}-[a-f0-9]{12}$/
promo.wildberries.ru /^[A-F0-9]{8}(?:-[A-F0-9]{4}){3}-[A-F0-9]{12}$/
taxi.yandex.ru /^[a-f0-9]{32}$/
mail.youdo.com
online.zcts.ru
mail.authorize.net
craigslist.org
maersk.com
monster.com
teamviewer.com
